language: go

dist: trusty

go:
  - 1.10.x

go_import_path: github.com/joefowler/gogetdata

before_install:
  - sudo add-apt-repository ppa:getdata/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install -y libgetdata
